### ISSUE TITLE
Issue with Running Notebook for Boltzmann Reweighted Sampling 

### ISSUE THREAD

**Issue by aakankschit** [PatWalters/TS#18]
Hi Pat,
I am from David Mobley's group at UCI and I am using your TS code for some virtual screening work. I am running into an error while using the notebook for the Boltzmann reweighted selection. It seems that you have an issue in the `thompson_sampling.py` script. On line 51 the `_warm_up_std` parameter is set to None. But is then used in the Boltzmann selection on line 66 `exp_terms = np.exp(scores / self._warmup_std)`. Which causes an error since the `_warm_up_std` is set to none. Thought that I would bring this to your attention.

**Comment by pfrstg** [comment]
Hi (this is the other Pat).

Thanks for the catch! 
_warmup_std is supposed to set supposed to be set during the warmup() function
It appears this was inadvertently removed in this commit
https://github.com/PatWalters/TS/commit/a5d0d898b41ba64d8777180ea2b657187ab97377
(see line 177).

Care to send an MR to put that one line back?

**Comment by aakankschit** [comment]
Hello,
I have made a PR with the change! Everything is working on the jupyter notebook for the Boltzmann reweighted sampling
